apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    expose: "true"
  annotations:
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: true
      kubernetes.io/ingress.class: tools-ingress
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30902
    targetPort: web
  selector:
    app: grafana
