apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
    expose: "true"
  annotations:
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: true
      kubernetes.io/ingress.class: tools-ingress
  name: alertmanager-main
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: main
